### ISSUE TITLE
Most Recent commit broke Projects View

### ISSUE THREAD

**Issue by waynetheisinger** [Stillat/the-agency-starter-kit#4]
### What were you doing

1. I updated to the most recent version and tested links in the control panel. 
2. I was browsing to the Projects View in the backend.

### What did you expect to happen
To see all the projects in the starter kit
### What actually happened
No content was showing, and the the title was site.project_board rather than "Project Board"

**Comment by JohnathonKoster** [comment]
To fix the header, you can apply a similar change in your project like this commit:

https://github.com/Stillat/the-agency-starter-kit/commit/0751df2f12ea111ccd4d3f01b3fdcf2a24076879

To fix the project board, make sure you have the npm dependencies installed and the project has been built:

```bash
npm install
npm run dev
```
